/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:ddd86362-4df5-4550-aa82-8ddbf330ac7e",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_ITP985tNn",
    "aws_user_pools_web_client_id": "6513d6brt0tirjllb51qla53st",
    "oauth": {}
};


export default awsmobile;
